### ISSUE TITLE
Issue with precompiling assets in Rails app

### ISSUE THREAD

**Issue by afdev82** [ntkme/sassc-embedded-polyfill-ruby#1]
Hi,

first of all, many thanks for this project!

I've followed the install instructions in a Rails app (v6.1.5) that is using Sprockets (v4.0.3) and the `sassc-rails` gem (v2.1.2).
I added the two lines after the `sassc-rails` gem in my Gemfile:

```
gem 'sassc-rails', '2.1.2'
gem 'sassc', github: 'sass/sassc-ruby', ref: 'refs/pull/233/head'
gem 'sassc-embedded'
```

But if I try to precompile the assets (or I start the dev server), I get the following error:

```
$ RAILS_ENV=production bin/rake assets:precompile --trace
[SassC::FunctionsHandler] undefined method `[]' for nil:NilClass
rake aborted!
SassC::SyntaxError: /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:149:in `rescue in block (2 levels) in setup': Error: error in C function asset_url (Sass::ScriptError)
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:146:in `block (2 levels) in setup'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host/function_registry.rb:50:in `function_call'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host.rb:118:in `function_call_request'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `public_send'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `block in receive_message'
/home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:243:in `compute_asset_extname': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:195:in `asset_path'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:90:in `asset_path'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:98:in `asset_url'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:147:in `block (2 levels) in setup'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host/function_registry.rb:50:in `function_call'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host.rb:118:in `function_call_request'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `public_send'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `block in receive_message'
app/assets/stylesheets/_font-awesome.scss:12

Caused by:
Sass::CompileError: /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:149:in `rescue in block (2 levels) in setup': Error: error in C function asset_url (Sass::ScriptError)
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:146:in `block (2 levels) in setup'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host/function_registry.rb:50:in `function_call'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host.rb:118:in `function_call_request'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `public_send'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `block in receive_message'
/home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:243:in `compute_asset_extname': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:195:in `asset_path'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:90:in `asset_path'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:98:in `asset_url'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sassc-embedded-1.0.4/lib/sassc/embedded.rb:147:in `block (2 levels) in setup'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host/function_registry.rb:50:in `function_call'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/host.rb:118:in `function_call_request'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `public_send'
        from /home/antonio/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sass-embedded-1.2.2/lib/sass/embedded/dispatcher.rb:82:in `block in receive_message'

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
I tried also to use the [sass-migrator](https://sass-lang.com/documentation/cli/migrator) to update my files, but it didn't help.

This is the fragment of the file with the error:

```
$fa-font-path: '@fortawesome/fontawesome-free/webfonts';

@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/brands';

@font-face {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  font-weight: 900;
  font-display: $fa-font-display;
  src:
    asset-url('#{$fa-font-path}/fa-solid-900.woff2') format('woff2'),
    asset-url('#{$fa-font-path}/fa-solid-900.woff') format('woff'),
    asset-url('#{$fa-font-path}/fa-solid-900.ttf') format('truetype');
}
```

It would be great to solve this problem and if I can help in some way just tell me.
Thank you for your support!

**Comment by ntkme** [comment]
The polyfill missed `.compact` that was in the original sassc: https://github.com/sass/sassc-ruby/blob/4fce2b635ca5d616a8b1381c64846410bc785ea4/lib/sassc/functions_handler.rb#L57

**Comment by afdev82** [comment]
Thank you for the fast response.
I tested it and it's working now!

**Comment by ntkme** [comment]
Good to know. GitHub is having issue right now. I will cut a release when GitHub gets back to normal operation.
