### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by afdev82** [ntkme/sassc-embedded-polyfill-ruby#4]
After the update from v1.2.0 to v1.5.1 I get this error in my tests and in my app (Ruby on Rails):

```
Failure/Error: <%= stylesheet_link_tag 'mirror', media: 'all', 'data-turbolinks-track' => true %>

      ActionView::Template::Error:
        Can't find stylesheet to import.
      # /usr/local/bundle/gems/sassc-embedded-1.5.2/lib/sassc/embedded.rb:51:in `rescue in render'
      # /usr/local/bundle/gems/sassc-embedded-1.5.2/lib/sassc/embedded.rb:14:in `render'
      # /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/utils.rb:141:in `module_include'
      # /usr/local/bundle/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:39:in `call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:33:in `call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/bundle.rb:27:in `call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/bundle.rb:32:in `block in call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/bundle.rb:31:in `call'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/base.rb:81:in `find_asset'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/base.rb:88:in `find_all_linked_assets'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `each'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `to_a'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/immediate_executor.rb:29:in `post'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:563:in `realize'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:250:in `execute'
      # /usr/local/bundle/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:297:in `execute'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:124:in `block in find'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:123:in `map'
      # /usr/local/bundle/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:123:in `find'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:53:in `each'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:53:in `map'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:53:in `precompiled_assets'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:38:in `asset_precompiled?'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:266:in `block (3 levels) in <class:Railtie>'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:368:in `precompiled?'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:338:in `digest_path'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:326:in `asset_path'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:103:in `block in resolve_asset_path'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `each'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `detect'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:102:in `resolve_asset_path'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:80:in `compute_asset_path'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:203:in `asset_path'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/helpers/asset_url_helper.rb:348:in `stylesheet_path'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:161:in `block in stylesheet_link_tag'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:160:in `map'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/helpers/asset_tag_helper.rb:160:in `stylesheet_link_tag'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:186:in `block in stylesheet_link_tag'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:184:in `map'
      # /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:184:in `stylesheet_link_tag'
      # ./app/views/layouts/mirror.html.erb:10:in `_app_views_layouts_mirror_html_erb___3220360303617532381_520720'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/base.rb:247:in `public_send'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/base.rb:247:in `_run'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/template.rb:154:in `block in render'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `block in instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `instrument'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/template.rb:345:in `instrument_render_template'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/template.rb:152:in `render'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `block in instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `instrument'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
      # /usr/local/bundle/bundler/gems/solidus_multi_domain-3f888260801a/app/decorators/lib/solidus_multi_domain/action_view/template_renderer_decorator.rb:9:in `render_template'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/template_renderer.rb:11:in `render'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/rendering.rb:117:in `block in _render_template'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/base.rb:273:in `in_rendering_context'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/rendering.rb:116:in `_render_template'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/streaming.rb:218:in `_render_template'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/rendering.rb:103:in `render_to_body'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/abstract_controller/rendering.rb:25:in `render'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:36:in `render'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/core_ext/benchmark.rb:14:in `ms'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
      # /usr/local/bundle/gems/activerecord-6.1.5/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:45:in `render'
      # ./app/controllers/mirrors_controller.rb:68:in `index'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/abstract_controller/base.rb:228:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
      # ./app/controllers/mirrors_controller.rb:219:in `use_time_zone'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
      # /usr/local/bundle/gems/actiontext-6.1.5/lib/action_text/rendering.rb:20:in `with_renderer'
      # /usr/local/bundle/gems/actiontext-6.1.5/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `instance_exec'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
      # /usr/local/bundle/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:137:in `run_callbacks'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `block in instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/notifications.rb:203:in `instrument'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
      # /usr/local/bundle/gems/activerecord-6.1.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/abstract_controller/base.rb:165:in `process'
      # /usr/local/bundle/gems/actionview-6.1.5/lib/action_view/rendering.rb:39:in `process'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal.rb:190:in `dispatch'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_controller/metal.rb:254:in `dispatch'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:33:in `serve'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `each'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/journey/router.rb:32:in `serve'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:842:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/bullet-7.0.1/lib/bullet/rack.rb:15:in `call'
      # /usr/local/bundle/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
      # /usr/local/bundle/gems/omniauth-2.0.4/lib/omniauth/builder.rb:45:in `call'
      # /usr/local/bundle/gems/dragonfly-1.4.0/lib/dragonfly/middleware.rb:14:in `call'
      # /usr/local/bundle/gems/dragonfly-1.4.0/lib/dragonfly/middleware.rb:14:in `call'
      # /usr/local/bundle/gems/rack-attack-6.6.0/lib/rack/attack.rb:103:in `call'
      # /usr/local/bundle/gems/rack-attack-6.6.0/lib/rack/attack.rb:110:in `call'
      # /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
      # /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
      # /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/cookies.rb:689:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
      # /usr/local/bundle/gems/railties-6.1.5/lib/rails/rack/logger.rb:37:in `call_app'
      # /usr/local/bundle/gems/railties-6.1.5/lib/rails/rack/logger.rb:26:in `block in call'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/tagged_logging.rb:37:in `tagged'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/tagged_logging.rb:99:in `tagged'
      # /usr/local/bundle/gems/railties-6.1.5/lib/rails/rack/logger.rb:26:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
      # /usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/request_id.rb:26:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
      # /usr/local/bundle/gems/activesupport-6.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
      # /usr/local/bundle/gems/dragonfly-1.4.0/lib/dragonfly/cookie_monster.rb:9:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/static.rb:24:in `call'
      # /usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
      # /usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
      # /usr/local/bundle/gems/railties-6.1.5/lib/rails/engine.rb:539:in `call'
      # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
      # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
      # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/testing/integration.rb:279:in `process'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/testing/integration.rb:16:in `get'
      # /usr/local/bundle/gems/actionpack-6.1.5/lib/action_dispatch/testing/integration.rb:372:in `get'
      # /usr/local/bundle/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
      # ./spec/requests/mirrors_spec.rb:14:in `block (3 levels) in <top (required)>'
      # /usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Sass::CompileError:
      #   Can't find stylesheet to import.
      #   /usr/local/bundle/gems/sass-embedded-1.3.2/lib/sass/embedded/protofier.rb:16:in `from_proto_compile_response'
```
I've had a look at which version I see this error for the first time and right after v1.2.0 (in v1.3.0) I have another one (`Sprockets::FileNotFound`) and from v1.3.1 I have the error in the title.

Thank you for your support.
Let me know if you need other info to solve the issue.

**Comment by ntkme** [comment]
`1.5.3` has been released to address an issue where importing filename with dot would fail: e.g. `@import "foo.bar"` would fail to load `foo.bar.scss`.

@afdev82 Can you please try and see if this fixes your issue?

**Comment by afdev82** [comment]
Now it's fixed, thank you!

It's strange, because the file I was importing doesn't have the dot in the name.
The source path is: `app/assets/stylesheets/mirror.scss`
The entry in my `app/assets/config/manifest.js`: `//= link mirror.css`
The import statement is: `stylesheet_link_tag 'mirror', media: 'all', 'data-turbolinks-track' => true`

**Comment by afdev82** [comment]
If you mean other files that were imported by `@import` inside the main file, at some point in one imported file there was

```
@import '../fonts/weathericons';
```

maybe this was the problem, I don't know.
